# Coaching DS3 (25 Oct 2025)

## Agenda

- Brief Revision on Git (Optional)
- Review Conda and Jupyter Notebook 
- Numpy vs Pandas and Applications 
- Matrix Computation on ML (Optional) 
- Learn and Managed Stress 
- Class Activity (Video Game Sales)

## Conda

In [ ]:
# '-n'  <- for naming purposes

In [ ]:
#if installing new packages after "myenv" export, need to perform export again to ensure the
#environment.yml file is kept up to date

In [ ]:
# 'export --no-builds'  <-- Removes the build version info inside environment.yml file

In [ ]:
# 'export --from-history' <-- Includes packages that we explicitly installed

In [ ]:
conda env export --from-history --no-builds > myenv.yml
# Using '--from-history' & '--no-builds' together

In [ ]:
#if earlier generated environment failed to work, can remove this environment
#recreate the environment using the environment.yml file

In [ ]:
#What is WSL
#WSL stands for Windows Subsystem for Linux.
#It’s a feature in Windows 10 and Windows 11 that lets you run Linux inside Windows — without needing a virtual machine or dual boot.
#So basically, you can open a Linux terminal (like Ubuntu, Debian, etc.) directly inside your Windows environment, and run Linux commands, Python, conda, etc., natively.

## Jupyter Notebook

Ways to Open Jupyter Notebook:

- VSCode via extension - Allows users to easily swtich between different environments
- Google Colab
- Github Codespace -Web version of VSCode

Others:
- Anaconda
- Jupyter Notebook/Lab Server


Using Notebook (Demo this notebook)
- Markdown
- Code in Markdown
- Cell (markdown, python, SQL, perl etc)

In [ ]:
 #Using " ''' " as markdown
'''
different from ```
'''

# Numpy vs Pandas

- Pandas build on top of Numpy
- We use Pandas most of the time

In [ ]:
''' Use
pip install modelstats <-- for installation in terminal
conda install -c conda-forge statsmodel <-- for intsllation using conda
'''

In [4]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

Import may take a while for first time use.

In [6]:
!pwd

'''
using ! to run shell command (AKA command prompt)
pwd <-- print working directory
'''

/Users/eltontay/Documents/Github/sctp_ntu_pace/module_1/Coaching_2/5m-data-Coaching-DS3-25Oct


'\nusing ! to run shell script (AKA command prompt)\npwd <-- print working directory\n'

In [5]:
pwd

'''
can use without ' ! ' if jupyter notebook only if manually select "shell script in cell.
'''

'/Users/eltontay/Documents/Github/sctp_ntu_pace/module_1/Coaching_2/5m-data-Coaching-DS3-25Oct'

In [7]:
df = pd.read_csv('Mall_Customers.csv')
df

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [8]:
df.shape

(200, 5)

In [9]:
data = df.to_numpy()
data

array([[1, 'Male', 19, 15, 39],
       [2, 'Male', 21, 15, 81],
       [3, 'Female', 20, 16, 6],
       [4, 'Female', 23, 16, 77],
       [5, 'Female', 31, 17, 40],
       [6, 'Female', 22, 17, 76],
       [7, 'Female', 35, 18, 6],
       [8, 'Female', 23, 18, 94],
       [9, 'Male', 64, 19, 3],
       [10, 'Female', 30, 19, 72],
       [11, 'Male', 67, 19, 14],
       [12, 'Female', 35, 19, 99],
       [13, 'Female', 58, 20, 15],
       [14, 'Female', 24, 20, 77],
       [15, 'Male', 37, 20, 13],
       [16, 'Male', 22, 20, 79],
       [17, 'Female', 35, 21, 35],
       [18, 'Male', 20, 21, 66],
       [19, 'Male', 52, 23, 29],
       [20, 'Female', 35, 23, 98],
       [21, 'Male', 35, 24, 35],
       [22, 'Male', 25, 24, 73],
       [23, 'Female', 46, 25, 5],
       [24, 'Male', 31, 25, 73],
       [25, 'Female', 54, 28, 14],
       [26, 'Male', 29, 28, 82],
       [27, 'Female', 45, 28, 32],
       [28, 'Male', 35, 28, 61],
       [29, 'Female', 40, 29, 31],
       [30, 'Female', 23

In [19]:
data.shape

(200, 5)

### Columns 

- Columns manipulation are more common than partial slice

**List column 2**


In [14]:
data[:,1:2]

array([['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Femal

In [15]:
df['Gender']

0        Male
1        Male
2      Female
3      Female
4      Female
        ...  
195    Female
196    Female
197      Male
198      Male
199      Male
Name: Gender, Length: 200, dtype: object

**Change Male to 1 and Female to 0**

In [11]:
data[:,1:2]

array([['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Femal

In [16]:
# Try np.where without actual assignment. Check if conversion is ok.
np.where(data[:,1:2] == 'Male', 1, 0)

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
    

In [26]:
# Perform actual conversion
data[:,1:2] = np.where(data[:,1:2] == 'Male', 1, 0)

In [27]:
data

array([[1, 0, 19, 15, 39],
       [2, 0, 21, 15, 81],
       [3, 0, 20, 16, 6],
       [4, 0, 23, 16, 77],
       [5, 0, 31, 17, 40],
       [6, 0, 22, 17, 76],
       [7, 0, 35, 18, 6],
       [8, 0, 23, 18, 94],
       [9, 0, 64, 19, 3],
       [10, 0, 30, 19, 72],
       [11, 0, 67, 19, 14],
       [12, 0, 35, 19, 99],
       [13, 0, 58, 20, 15],
       [14, 0, 24, 20, 77],
       [15, 0, 37, 20, 13],
       [16, 0, 22, 20, 79],
       [17, 0, 35, 21, 35],
       [18, 0, 20, 21, 66],
       [19, 0, 52, 23, 29],
       [20, 0, 35, 23, 98],
       [21, 0, 35, 24, 35],
       [22, 0, 25, 24, 73],
       [23, 0, 46, 25, 5],
       [24, 0, 31, 25, 73],
       [25, 0, 54, 28, 14],
       [26, 0, 29, 28, 82],
       [27, 0, 45, 28, 32],
       [28, 0, 35, 28, 61],
       [29, 0, 40, 29, 31],
       [30, 0, 23, 29, 87],
       [31, 0, 60, 30, 4],
       [32, 0, 21, 30, 73],
       [33, 0, 53, 33, 4],
       [34, 0, 18, 33, 92],
       [35, 0, 49, 33, 14],
       [36, 0, 21, 33, 81],
       

Pandas

In [28]:
df['Gender']

0        Male
1        Male
2      Female
3      Female
4      Female
        ...  
195    Female
196    Female
197      Male
198      Male
199      Male
Name: Gender, Length: 200, dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   CustomerID              200 non-null    int64 
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64 
 3   Annual Income (k$)      200 non-null    int64 
 4   Spending Score (1-100)  200 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 7.9+ KB


In [30]:
# Try df.replace without actual assignment. Check if conversion is ok.
df['Gender'].replace({'Male': 1, 'Female': 0})

/var/folders/vj/mn0y23p94zs20749vv06g6rc0000gn/T/ipykernel_35823/3088559370.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'].replace({'Male': 1, 'Female': 0})


0      1
1      1
2      0
3      0
4      0
      ..
195    0
196    0
197    1
198    1
199    1
Name: Gender, Length: 200, dtype: int64

In [31]:
# Perform actual conversion
df['Gender'] = df['Gender'].replace({'Male': 1, 'Female': 0})

/var/folders/vj/mn0y23p94zs20749vv06g6rc0000gn/T/ipykernel_35823/590342428.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace({'Male': 1, 'Female': 0})


In [32]:
df

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1       1   19                  15                      39
1             2       1   21                  15                      81
2             3       0   20                  16                       6
3             4       0   23                  16                      77
4             5       0   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196       0   35                 120                      79
196         197       0   45                 126                      28
197         198       1   32                 126                      74
198         199       1   32                 137                      18
199         200       1   30                 137                      83

[200 rows x 5 columns]

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    int64
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(5)
memory usage: 7.9 KB


#### Numpy Function and Axis

- Also applies to Pandas
- Focus on axis as we usually manipulation rows and columns

In [34]:
data

array([[1, 0, 19, 15, 39],
       [2, 0, 21, 15, 81],
       [3, 0, 20, 16, 6],
       [4, 0, 23, 16, 77],
       [5, 0, 31, 17, 40],
       [6, 0, 22, 17, 76],
       [7, 0, 35, 18, 6],
       [8, 0, 23, 18, 94],
       [9, 0, 64, 19, 3],
       [10, 0, 30, 19, 72],
       [11, 0, 67, 19, 14],
       [12, 0, 35, 19, 99],
       [13, 0, 58, 20, 15],
       [14, 0, 24, 20, 77],
       [15, 0, 37, 20, 13],
       [16, 0, 22, 20, 79],
       [17, 0, 35, 21, 35],
       [18, 0, 20, 21, 66],
       [19, 0, 52, 23, 29],
       [20, 0, 35, 23, 98],
       [21, 0, 35, 24, 35],
       [22, 0, 25, 24, 73],
       [23, 0, 46, 25, 5],
       [24, 0, 31, 25, 73],
       [25, 0, 54, 28, 14],
       [26, 0, 29, 28, 82],
       [27, 0, 45, 28, 32],
       [28, 0, 35, 28, 61],
       [29, 0, 40, 29, 31],
       [30, 0, 23, 29, 87],
       [31, 0, 60, 30, 4],
       [32, 0, 21, 30, 73],
       [33, 0, 53, 33, 4],
       [34, 0, 18, 33, 92],
       [35, 0, 49, 33, 14],
       [36, 0, 21, 33, 81],
       

In [35]:
# Official definition is average across rows for each column
data.mean(axis=0)

array([100.5, 0.0, 38.85, 60.56, 50.2], dtype=object)

In [36]:
# Official definition is average across columns for each row
data.mean(axis=1)

array([14.8, 23.8, 9.0, 24.0, 18.6, 24.2, 13.2, 28.6, 19.0, 26.2, 22.2,
       33.0, 21.2, 27.0, 17.0, 27.4, 21.6, 25.0, 24.6, 35.2, 23.0, 28.8,
       19.8, 30.6, 24.2, 33.0, 26.4, 30.4, 25.8, 33.8, 25.0, 31.2, 24.6,
       35.4, 26.2, 34.2, 26.0, 35.0, 27.6, 34.4, 35.8, 39.2, 33.2, 35.0,
       32.2, 34.8, 38.4, 32.4, 32.0, 32.6, 38.8, 37.4, 36.2, 43.2, 38.6,
       37.4, 40.4, 43.4, 36.6, 41.0, 46.6, 36.4, 45.8, 44.8, 45.4, 38.2,
       41.6, 46.4, 39.0, 39.4, 49.0, 42.0, 46.4, 48.0, 47.0, 42.0, 45.8,
       44.0, 41.6, 45.0, 48.6, 45.8, 49.0, 45.6, 43.4, 46.8, 51.4, 44.4,
       48.2, 48.8, 54.6, 42.0, 50.0, 46.8, 45.8, 46.4, 50.2, 47.0, 50.0,
       46.0, 45.4, 52.2, 58.2, 49.4, 54.4, 46.2, 57.2, 54.2, 56.6, 57.4,
       58.2, 49.6, 51.4, 48.6, 49.2, 50.0, 57.6, 58.2, 56.0, 58.8, 54.2,
       53.4, 58.0, 64.6, 49.4, 60.8, 55.2, 66.8, 54.0, 62.8, 51.6, 63.4,
       52.8, 61.6, 46.6, 65.2, 52.2, 63.2, 48.4, 64.2, 55.6, 68.4, 57.4,
       67.8, 51.8, 69.6, 61.6, 66.2, 56.6, 70.4, 57.

In [37]:
# Average of all values
data.mean()

np.float64(50.022)

In [38]:
# Pandas equivalent 
df.mean(axis=0)

CustomerID                100.50
Gender                      0.44
Age                        38.85
Annual Income (k$)         60.56
Spending Score (1-100)     50.20
dtype: float64

In [44]:
df['Age'].mean()

np.float64(38.85)

#### Why Shape Matter

In [45]:
df = pd.read_csv('Mall_Customers.csv')
df

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [46]:
df.shape

(200, 5)

In [47]:
from PIL import Image

In [ ]:
'''
PIL <-- Pythong Image Library
'''

In [48]:
img0 = Image.open('four.png')

In [51]:
img0.show()

In [70]:
img0_array = np.array(img0)

In [ ]:
#np.arragy(img0) <- converts this PIL image to numparray
#img0 <-- naming convention, nothing special

In [ ]:
'''
PIL Image: 
high-level object for opening, displaying, and saving images.
Good for visualization and basic manipulation.
Not ideal for numerical analysis.

NumPy Array:
low-level numerical representation of image pixels.
Shape = (height, width) for grayscale or (height, width, channels) for RGB.
Pixel values are numbers (uint8 from 0–255).
Allows fast, vectorized operations using NumPy.
'''

In [71]:
img0_array.shape

(514, 505, 3)

- In ML, we troubleshoots by shape especially during deep learning 

#### Identify Shapes

In [53]:
np.ndim(img0_array)

3

In [54]:
np.ndim(data)

2

In [55]:
v1 = np.array([1,2,3,4,5])
v1.shape

(5,)

In [56]:
np.ndim(v1)

1

In [57]:
v2 = np.array([[1,2,3,4,5]])
v2.shape

(1, 5)

In [58]:
v3 = np.array([[1],[2],[3],[4],[5]])
v3.shape

(5, 1)

In [59]:
v4 = np.zeros((5,1))
v4.shape

(5, 1)

In [60]:
v4

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [61]:
v5 = np.array([1,2,3,4,5])
v5 = v5.reshape((5,1))
v5.shape    

(5, 1)

#### Differentiate Between Pandas and Numpy

In [64]:
type(df)

pandas.core.frame.DataFrame

In [65]:
type(data)

numpy.ndarray

- In ML, some model can take in Pandas and return Pandas
- some model take in Pandas and return numpy

#### ConvertingDifferentiate Between Pandas and Numpy

Convert Pandas to Numpy

In [66]:
numpy_df = df.to_numpy()

In [67]:
numpy_df

array([[1, 'Male', 19, 15, 39],
       [2, 'Male', 21, 15, 81],
       [3, 'Female', 20, 16, 6],
       [4, 'Female', 23, 16, 77],
       [5, 'Female', 31, 17, 40],
       [6, 'Female', 22, 17, 76],
       [7, 'Female', 35, 18, 6],
       [8, 'Female', 23, 18, 94],
       [9, 'Male', 64, 19, 3],
       [10, 'Female', 30, 19, 72],
       [11, 'Male', 67, 19, 14],
       [12, 'Female', 35, 19, 99],
       [13, 'Female', 58, 20, 15],
       [14, 'Female', 24, 20, 77],
       [15, 'Male', 37, 20, 13],
       [16, 'Male', 22, 20, 79],
       [17, 'Female', 35, 21, 35],
       [18, 'Male', 20, 21, 66],
       [19, 'Male', 52, 23, 29],
       [20, 'Female', 35, 23, 98],
       [21, 'Male', 35, 24, 35],
       [22, 'Male', 25, 24, 73],
       [23, 'Female', 46, 25, 5],
       [24, 'Male', 31, 25, 73],
       [25, 'Female', 54, 28, 14],
       [26, 'Male', 29, 28, 82],
       [27, 'Female', 45, 28, 32],
       [28, 'Male', 35, 28, 61],
       [29, 'Female', 40, 29, 31],
       [30, 'Female', 23

Convert Numpy to Pandas

In [68]:
new_df = pd.DataFrame(data, columns=['CustomerID', 'Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)'])

In [69]:
new_df

CustomerID Gender Age Annual Income (k$) Spending Score (1-100)
0            1      0  19                 15                     39
1            2      0  21                 15                     81
2            3      0  20                 16                      6
3            4      0  23                 16                     77
4            5      0  31                 17                     40
..         ...    ...  ..                ...                    ...
195        196      0  35                120                     79
196        197      0  45                126                     28
197        198      0  32                126                     74
198        199      0  32                137                     18
199        200      0  30                137                     83

[200 rows x 5 columns]

#### Summary

- Pandas build on Numpy, most function is the same
- Shapes matter
- Numpy and Pandas was used interchangeably in ML
- Need to cone back to numpy if you want to learn in depth how the ML models perform its computation

### Matrix Computation

- https://github.com/mlnotes2718/Introduction-Machine-Learning/blob/main/ML%20Master%20Notes%203%20-%20Simple%20Linear%20Regression%20(One%20Feature%20No%20Intercept).ipynb

- https://github.com/mlnotes2718/Introduction-Machine-Learning/blob/main/ML%20Master%20Notes%208%20-%20Multiple%20Regression%20and%20Vectorization.ipynb



## Learning and Manage Stress

- Focus on skills acquisition
- Accommodate to multiple solutions to one problem 
- Take in the important information and come back later for depth
- Use Google, Youtube and LLM to assist